//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Projects struct {
	ID             int32 `sql:"primary_key"`
	Name           string
	Description    *string
	OrganizationID int32
	StartDate      *time.Time
	EndDate        *time.Time
	CreatedAt      *time.Time
	UpdatedAt      *time.Time
}
