version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: clochness_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: clochness
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    restart: always


volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
