// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/realm76/ranger/ent/node"
	"github.com/realm76/ranger/ent/nodetimeentry"
	"github.com/realm76/ranger/ent/predicate"
)

// NodeUpdate is the builder for updating Node entities.
type NodeUpdate struct {
	config
	hooks    []Hook
	mutation *NodeMutation
}

// Where appends a list predicates to the NodeUpdate builder.
func (nu *NodeUpdate) Where(ps ...predicate.Node) *NodeUpdate {
	nu.mutation.Where(ps...)
	return nu
}

// SetParentHandle sets the "parent_handle" field.
func (nu *NodeUpdate) SetParentHandle(s string) *NodeUpdate {
	nu.mutation.SetParentHandle(s)
	return nu
}

// SetNillableParentHandle sets the "parent_handle" field if the given value is not nil.
func (nu *NodeUpdate) SetNillableParentHandle(s *string) *NodeUpdate {
	if s != nil {
		nu.SetParentHandle(*s)
	}
	return nu
}

// ClearParentHandle clears the value of the "parent_handle" field.
func (nu *NodeUpdate) ClearParentHandle() *NodeUpdate {
	nu.mutation.ClearParentHandle()
	return nu
}

// SetTitle sets the "title" field.
func (nu *NodeUpdate) SetTitle(s string) *NodeUpdate {
	nu.mutation.SetTitle(s)
	return nu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (nu *NodeUpdate) SetNillableTitle(s *string) *NodeUpdate {
	if s != nil {
		nu.SetTitle(*s)
	}
	return nu
}

// SetHandle sets the "handle" field.
func (nu *NodeUpdate) SetHandle(s string) *NodeUpdate {
	nu.mutation.SetHandle(s)
	return nu
}

// SetNillableHandle sets the "handle" field if the given value is not nil.
func (nu *NodeUpdate) SetNillableHandle(s *string) *NodeUpdate {
	if s != nil {
		nu.SetHandle(*s)
	}
	return nu
}

// AddTimeEntryIDs adds the "time_entries" edge to the NodeTimeEntry entity by IDs.
func (nu *NodeUpdate) AddTimeEntryIDs(ids ...int) *NodeUpdate {
	nu.mutation.AddTimeEntryIDs(ids...)
	return nu
}

// AddTimeEntries adds the "time_entries" edges to the NodeTimeEntry entity.
func (nu *NodeUpdate) AddTimeEntries(n ...*NodeTimeEntry) *NodeUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nu.AddTimeEntryIDs(ids...)
}

// Mutation returns the NodeMutation object of the builder.
func (nu *NodeUpdate) Mutation() *NodeMutation {
	return nu.mutation
}

// ClearTimeEntries clears all "time_entries" edges to the NodeTimeEntry entity.
func (nu *NodeUpdate) ClearTimeEntries() *NodeUpdate {
	nu.mutation.ClearTimeEntries()
	return nu
}

// RemoveTimeEntryIDs removes the "time_entries" edge to NodeTimeEntry entities by IDs.
func (nu *NodeUpdate) RemoveTimeEntryIDs(ids ...int) *NodeUpdate {
	nu.mutation.RemoveTimeEntryIDs(ids...)
	return nu
}

// RemoveTimeEntries removes "time_entries" edges to NodeTimeEntry entities.
func (nu *NodeUpdate) RemoveTimeEntries(n ...*NodeTimeEntry) *NodeUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nu.RemoveTimeEntryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (nu *NodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, nu.sqlSave, nu.mutation, nu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nu *NodeUpdate) SaveX(ctx context.Context) int {
	affected, err := nu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nu *NodeUpdate) Exec(ctx context.Context) error {
	_, err := nu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nu *NodeUpdate) ExecX(ctx context.Context) {
	if err := nu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (nu *NodeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt))
	if ps := nu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nu.mutation.ParentHandle(); ok {
		_spec.SetField(node.FieldParentHandle, field.TypeString, value)
	}
	if nu.mutation.ParentHandleCleared() {
		_spec.ClearField(node.FieldParentHandle, field.TypeString)
	}
	if value, ok := nu.mutation.Title(); ok {
		_spec.SetField(node.FieldTitle, field.TypeString, value)
	}
	if value, ok := nu.mutation.Handle(); ok {
		_spec.SetField(node.FieldHandle, field.TypeString, value)
	}
	if nu.mutation.TimeEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.TimeEntriesTable,
			Columns: []string{node.TimeEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodetimeentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.RemovedTimeEntriesIDs(); len(nodes) > 0 && !nu.mutation.TimeEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.TimeEntriesTable,
			Columns: []string{node.TimeEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodetimeentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.TimeEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.TimeEntriesTable,
			Columns: []string{node.TimeEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodetimeentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, nu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	nu.mutation.done = true
	return n, nil
}

// NodeUpdateOne is the builder for updating a single Node entity.
type NodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NodeMutation
}

// SetParentHandle sets the "parent_handle" field.
func (nuo *NodeUpdateOne) SetParentHandle(s string) *NodeUpdateOne {
	nuo.mutation.SetParentHandle(s)
	return nuo
}

// SetNillableParentHandle sets the "parent_handle" field if the given value is not nil.
func (nuo *NodeUpdateOne) SetNillableParentHandle(s *string) *NodeUpdateOne {
	if s != nil {
		nuo.SetParentHandle(*s)
	}
	return nuo
}

// ClearParentHandle clears the value of the "parent_handle" field.
func (nuo *NodeUpdateOne) ClearParentHandle() *NodeUpdateOne {
	nuo.mutation.ClearParentHandle()
	return nuo
}

// SetTitle sets the "title" field.
func (nuo *NodeUpdateOne) SetTitle(s string) *NodeUpdateOne {
	nuo.mutation.SetTitle(s)
	return nuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (nuo *NodeUpdateOne) SetNillableTitle(s *string) *NodeUpdateOne {
	if s != nil {
		nuo.SetTitle(*s)
	}
	return nuo
}

// SetHandle sets the "handle" field.
func (nuo *NodeUpdateOne) SetHandle(s string) *NodeUpdateOne {
	nuo.mutation.SetHandle(s)
	return nuo
}

// SetNillableHandle sets the "handle" field if the given value is not nil.
func (nuo *NodeUpdateOne) SetNillableHandle(s *string) *NodeUpdateOne {
	if s != nil {
		nuo.SetHandle(*s)
	}
	return nuo
}

// AddTimeEntryIDs adds the "time_entries" edge to the NodeTimeEntry entity by IDs.
func (nuo *NodeUpdateOne) AddTimeEntryIDs(ids ...int) *NodeUpdateOne {
	nuo.mutation.AddTimeEntryIDs(ids...)
	return nuo
}

// AddTimeEntries adds the "time_entries" edges to the NodeTimeEntry entity.
func (nuo *NodeUpdateOne) AddTimeEntries(n ...*NodeTimeEntry) *NodeUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nuo.AddTimeEntryIDs(ids...)
}

// Mutation returns the NodeMutation object of the builder.
func (nuo *NodeUpdateOne) Mutation() *NodeMutation {
	return nuo.mutation
}

// ClearTimeEntries clears all "time_entries" edges to the NodeTimeEntry entity.
func (nuo *NodeUpdateOne) ClearTimeEntries() *NodeUpdateOne {
	nuo.mutation.ClearTimeEntries()
	return nuo
}

// RemoveTimeEntryIDs removes the "time_entries" edge to NodeTimeEntry entities by IDs.
func (nuo *NodeUpdateOne) RemoveTimeEntryIDs(ids ...int) *NodeUpdateOne {
	nuo.mutation.RemoveTimeEntryIDs(ids...)
	return nuo
}

// RemoveTimeEntries removes "time_entries" edges to NodeTimeEntry entities.
func (nuo *NodeUpdateOne) RemoveTimeEntries(n ...*NodeTimeEntry) *NodeUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nuo.RemoveTimeEntryIDs(ids...)
}

// Where appends a list predicates to the NodeUpdate builder.
func (nuo *NodeUpdateOne) Where(ps ...predicate.Node) *NodeUpdateOne {
	nuo.mutation.Where(ps...)
	return nuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (nuo *NodeUpdateOne) Select(field string, fields ...string) *NodeUpdateOne {
	nuo.fields = append([]string{field}, fields...)
	return nuo
}

// Save executes the query and returns the updated Node entity.
func (nuo *NodeUpdateOne) Save(ctx context.Context) (*Node, error) {
	return withHooks(ctx, nuo.sqlSave, nuo.mutation, nuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nuo *NodeUpdateOne) SaveX(ctx context.Context) *Node {
	node, err := nuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nuo *NodeUpdateOne) Exec(ctx context.Context) error {
	_, err := nuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nuo *NodeUpdateOne) ExecX(ctx context.Context) {
	if err := nuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (nuo *NodeUpdateOne) sqlSave(ctx context.Context) (_node *Node, err error) {
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt))
	id, ok := nuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Node.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := nuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, node.FieldID)
		for _, f := range fields {
			if !node.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != node.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := nuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nuo.mutation.ParentHandle(); ok {
		_spec.SetField(node.FieldParentHandle, field.TypeString, value)
	}
	if nuo.mutation.ParentHandleCleared() {
		_spec.ClearField(node.FieldParentHandle, field.TypeString)
	}
	if value, ok := nuo.mutation.Title(); ok {
		_spec.SetField(node.FieldTitle, field.TypeString, value)
	}
	if value, ok := nuo.mutation.Handle(); ok {
		_spec.SetField(node.FieldHandle, field.TypeString, value)
	}
	if nuo.mutation.TimeEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.TimeEntriesTable,
			Columns: []string{node.TimeEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodetimeentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.RemovedTimeEntriesIDs(); len(nodes) > 0 && !nuo.mutation.TimeEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.TimeEntriesTable,
			Columns: []string{node.TimeEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodetimeentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.TimeEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.TimeEntriesTable,
			Columns: []string{node.TimeEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodetimeentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Node{config: nuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, nuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	nuo.mutation.done = true
	return _node, nil
}
